on:
  push:

name: test needs

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      run: 'false'

  second:
    needs:
    - first
    runs-on: ubuntu-latest
    if: (success() || failure())
    steps:
    - name: failed?
      if: failure()
      run: echo 'failed?'
    
    - name: success!
      run: echo 'success!'

    - name: first failed
      if: needs.first.result == 'failure'
      run: echo 'first failed!'

    - name: pass?
      run: echo 'I guess?'
